# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - journey-api

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore JourneyService
        run: dotnet restore ./JourneyService/JourneyService.csproj

      - name: Build JourneyService
        run: >
          dotnet build
          ./JourneyService/JourneyService.csproj
          --configuration Release
          --no-restore

      - name: Publish JourneyService
        run: >
          dotnet publish
          ./JourneyService/JourneyService.csproj
          --configuration Release
          --no-build
          --output ./journey-publish

      - name: Verify publish output
        shell: pwsh
        run: |
          Get-ChildItem ./journey-publish

          if (-not (Test-Path "./journey-publish/JourneyService.dll")) {
              throw "JourneyService.dll was not found in the publish output."
          }

      - name: Upload JourneyService artifact
        uses: actions/upload-artifact@v4
        with:
          name: journey-service-app
          path: ./journey-publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: journey-service-app
          path: ./journey-publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AFD9F0AF8D32492E9800FB9BA9454608 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CCA410647D994D8596CA2A9EE63FA5D6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_443AAA9122E84B6B82802BBFC7FE3323 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'journey-api'
          slot-name: 'Production'
          package: ./journey-publish
          
